/**
 * Build-time encryption for sensitive secrets
 * Encrypts REWARD_SENDER_NWC and ATTESTATION_NSEC so they don't appear
 * as plaintext in APK
 *
 * Usage: node scripts/encrypt-secrets.cjs
 * Run before building APK to generate encrypted secrets file
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// Load environment variables
require('dotenv').config();

// Key derivation components (must match runtime decryptor)
const KEY_PARTS = {
  part1: 'rn-str-2025-v1', // APP_META.buildId
  part2: 'com.anon', // Bundle ID prefix (first 8 chars)
  part3: 'x7k9m2', // FEATURE_CONFIG._internalFlags.experimentId
  part4: 'nwc-v1-2025', // PROTOCOL_VERSION
};

/**
 * Derive encryption key from scattered components
 * Same algorithm used at runtime for decryption
 */
function deriveKey() {
  const combined = `${KEY_PARTS.part1}:${KEY_PARTS.part2}:${KEY_PARTS.part3}:${KEY_PARTS.part4}`;
  return crypto.createHash('sha256').update(combined).digest();
}

/**
 * Encrypt a string using AES-256-GCM
 * Returns ciphertext, IV, and auth tag (all base64 encoded)
 */
function encrypt(plaintext) {
  const key = deriveKey();
  const iv = crypto.randomBytes(12); // GCM standard: 12-byte IV

  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  let ciphertext = cipher.update(plaintext, 'utf8', 'base64');
  ciphertext += cipher.final('base64');

  const authTag = cipher.getAuthTag();

  return {
    c: ciphertext, // ciphertext
    i: iv.toString('base64'), // initialization vector
    t: authTag.toString('base64'), // authentication tag
  };
}

/**
 * Main encryption routine
 */
function main() {
  console.log('Encrypting secrets...\n');

  // Get NWC from environment
  const nwc = process.env.REWARD_SENDER_NWC;
  const attestationNsec = process.env.ATTESTATION_NSEC;

  let hasNwc = false;
  let hasAttestation = false;
  let encryptedNwc = null;
  let encryptedAttestation = null;

  // Encrypt NWC if present
  if (nwc) {
    if (!nwc.startsWith('nostr+walletconnect://')) {
      console.error('ERROR: REWARD_SENDER_NWC does not look like a valid NWC string');
      process.exit(1);
    }
    encryptedNwc = encrypt(nwc);
    hasNwc = true;
    console.log('Encrypted REWARD_SENDER_NWC');
  } else {
    console.warn('WARNING: REWARD_SENDER_NWC not found in .env (skipping)');
  }

  // Encrypt attestation nsec if present
  if (attestationNsec) {
    if (!attestationNsec.startsWith('nsec1')) {
      console.error('ERROR: ATTESTATION_NSEC does not look like a valid nsec');
      process.exit(1);
    }
    encryptedAttestation = encrypt(attestationNsec);
    hasAttestation = true;
    console.log('Encrypted ATTESTATION_NSEC');
  } else {
    console.warn('WARNING: ATTESTATION_NSEC not found in .env (skipping)');
    console.warn('Run: node scripts/generate-attestation-key.cjs to create one');
  }

  if (!hasNwc && !hasAttestation) {
    console.error('\nERROR: No secrets found to encrypt!');
    console.error('Add REWARD_SENDER_NWC and/or ATTESTATION_NSEC to .env');
    process.exit(1);
  }

  // Generate TypeScript output
  let output = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: node scripts/encrypt-secrets.cjs
// Regenerate after changing secrets in .env

/**
 * Encrypted secrets for runtime decryption
 * These values are decrypted using secretDecryptor.ts
 */
`;

  if (encryptedNwc) {
    output += `\nexport const ENCRYPTED_REWARD_NWC = ${JSON.stringify(encryptedNwc, null, 2)};\n`;
  } else {
    output += `\nexport const ENCRYPTED_REWARD_NWC = null;\n`;
  }

  if (encryptedAttestation) {
    output += `\nexport const ENCRYPTED_ATTESTATION_NSEC = ${JSON.stringify(encryptedAttestation, null, 2)};\n`;
  } else {
    output += `\nexport const ENCRYPTED_ATTESTATION_NSEC = null;\n`;
  }

  // Write to src/config/encryptedSecrets.ts
  const outputPath = path.join(__dirname, '../src/config/encryptedSecrets.ts');
  fs.writeFileSync(outputPath, output);

  console.log(`\nOutput written to: src/config/encryptedSecrets.ts`);

  if (hasNwc) {
    console.log('\nNWC ciphertext length:', encryptedNwc.c.length, 'chars');
  }
  if (hasAttestation) {
    console.log('Attestation ciphertext length:', encryptedAttestation.c.length, 'chars');
  }

  console.log('\nThe APK will no longer contain plaintext secrets.');
  console.log('- No "nostr+walletconnect://" strings');
  console.log('- No "nsec1" strings');
}

main();
